```{r}

install.packages("RTextTools")
install.packages("tm")
install.packages("wordcloud")

```


```{r}
library(RTextTools)
## Loading required package: SparseM
## 
## Attaching package: 'SparseM'
## 
## The following object is masked from 'package:base':
## 
##     backsolve
library(tm)
## Loading required package: NLP
library(wordcloud)
## Loading required package: RColorBrewer
```


```{r}
letters

grep("[a-z]", letters)

grep("[A-Z]", letters)

grep("[AB]", letters)

grep("[AB]", letters,ignore.case = TRUE)

grep("[a-zA-Z]", letters)

grep("[azAZ]", letters)

seuss <- c("You have brains in your head.",
           "You have feet in your shoes.", 
           "You can steer yourself any direction you choose.",            
           "You're on your own.", 
           "And you know what you know.", 
           "And YOU are the one who'll decide where to go...",            
           "- Dr. Seuss")
grep("you", seuss)

if(length(i <- grep("in", seuss)))
  cat("'in' appears at least once in\n\t", seuss[i], "\n")

i # 1 and 2

seuss[i]

s<-gsub("([ab])", "\\1-z\\1_s", "abc vs, ABC  - Oh, A B C. It's easy as, 1 2 3. As simple as, do re mi. a b c, 1 2 3")
s

s<-gsub("([ab])", "-z_s", "abc vs, ABC  - Oh, A B C. It's easy as, 1 2 3. As simple as, do re mi. a b c, 1 2 3")
s

s<-gsub("([ab])", "\\a\\b", "abc vs, ABC  - Oh, A B C. It's easy as, 1 2 3. As simple as, do re mi. a b c, 1 2 3")
s

stop.words <- c("The", "for", "are",
          "to",  "your", 
         "to", "and", "the", 
         "is", "your",  "and", "is",
         "it", "for", "all", "its", "it's")

seuss.re<-regexpr("[ ]+",seuss)
seuss.re

seuss.re<-gregexpr("[ ]+",seuss)
seuss.re

str <- " You have brains in your head      "
str

str<-sub("[ ]+$", "", str)  ## trailing spaces only
str

str<-sub("^[ ]+", "", str)  ## leading spaces only
str

sub("[[:space:]]+$", "", str) ## white space, POSIX-style

sub("\\s+$", "", str, perl = TRUE) ## Perl-style white space

txt <- "You have brains in your head"
gsub("(\\w)(\\w*)", "\\U\\1\\L\\2", txt, perl=TRUE)

gsub("\\b(\\w)",    "\\U\\1",       txt, perl=TRUE)

txt2 <- "You have feet in your shoes."
gsub("(\\w)(\\w*)(\\w)", "\\U\\1\\E\\2\\U\\3", txt2, perl=TRUE)

sub("(\\w)(\\w*)(\\w)", "\\U\\1\\E\\2\\U\\3", txt2, perl=TRUE)
```

```{r}
url <- "http://nikbearbrown/machine/learning/"
m <- regexec("^(([^:]+)://)?([^:/]+)(:([0-9]+))?(/.*)", url)
m

regmatches(url, m)

URL_parts <- function(u) {
  m <- regexec("^(([^:]+)://)?([^:/]+)(:([0-9]+))?(/.*)", u)
  parts <- do.call(rbind,
                   lapply(regmatches(u, m), `[`, c(3L, 4L, 6L, 7L)))
  colnames(parts) <- c("protocol","host","port","path")
  parts
}
URL_parts(url)
```


```{r}
# Spilt text
seuss

seuss[1]

sp<-strsplit(seuss[1], "a") # "You have brains in your head."
sp
s<-"You    have   brains  in  your head. "
sp<-strsplit(seuss[1], " ") 
sp

sp<-strsplit(s," ") 
sp

sp<-strsplit(s,"[ ]+") 
sp

sp<-strsplit(s,"[ ]+",perl = TRUE) 
sp




```


```{r}
seuss <- c("You have brains in your head.",
           "You have feet in your shoes.", 
           "You can steer yourself any direction you choose.",            
           "You're on your own.", 
           "And you know what you know.", 
           "And YOU are the one who'll decide where to go...",    
           "Today you are you, that is truer than true. There is no one alive who is youer than you. - Dr. Seuss",
           "Don't cry because it's over. Smile because it happened. - Dr. Seuss",       
           "Unless someone like you cares a whole awful lot, nothing is going to get better. It's not. - Dr. Seuss",
           "A person's a person, no matter how small. - Dr. Seuss",       
           "Today is your day! Your mountain is waiting so get on your way! - Dr. Seuss", 
           "You're never too old, too wacky, too wild, to pick up a book and read to a child. - Dr. Seuss",
           "The more that you read, the more things you will know. The more that you learn, the more places you'll go. - Dr. Seuss",
           "Oh the things you can find if you don't stay behind! - Dr. Seuss",
           "And turtles, of course. all the turtles are FREE. As turtles and, maybe, ALL creatures should be. - Dr. Seuss",
           "With your head full of brains and your shoes full of feet, you're too smart to go down any not-so-good street. - Dr. Seuss",
           "You're on your own. And you know what you know. And you're the one who'll decide where to go. - Dr. Seuss", 
           "Sometimes the questions are complicated and the answers are simple. - Dr. Seuss",
           "You do not like them. So you say. Try them! Try them! And you may! - Dr. Seuss",
           "You have brains in your head, you have feet in your shoes. You can steer yourself any direction you choose. - Dr. Seuss",
           "If things start happening, don't worry. Don't stew. Just go right along. You'll start happening too. - Dr. Seuss", 
           "So be sure when you step. Step with care and great tact and remember that life's a Great Balancing Act. - Dr. Seuss",   
           "If you never did you should. These things are fun, and fun is good. - Dr. Seuss",
           "I have heard there are troubles of more than one kind. Some come from ahead and some come from behind. But I've bought a big bat. I'm all ready you see. Now my troubles are going to have troubles with me! - Dr. Seuss",
           "Will you succeed? Yes! You will, indeed! (98 and 3/4 percent guaranteed. - Dr. Seuss",   
           "You're off to Great Places!",
           "Today is your day!",
           "Your mountain is waiting,",
           "So... get on your way!",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "So be sure when you step, Step with care and great tact. And remember that life's A Great Balancing Act. And will you succeed? Yes! You will, indeed! ( and ? percent guaranteed) Kid, you'll move mountains.",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "You'll get mixed up, of course, as you already know. You'll get mixed up with many strange birds as you go. So be sure when you step. Step with care and great tact and remember that Life's a Great Balancing Act. Just never forget to be dexterous and deft. And never mix up your right foot with your left.",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "Oh the places you'll go! There is fun to be done! There are points to be scored. There are games to be won. And the magical things you can do with that ball will make you the winning-est winner of all.",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "Things may happen and often do to people as brainy and footsy as you",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "Congratulations!",
           "Today is your day.",
           "You're off to Great Places!",
           "You're off and away!",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "It's opener, out there, in the wide, open air.",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "You have brains in your head.",
           "You have feet in your shoes.",
           "You can steer yourself any direction you choose.",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "And when you're alone there's a very good chance",
           "you'll meet things that scare you right out of your pants",
           "There are some, down the road between hither and yon,",
           "that can scare you so much you won't want to go on.",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "You will come to a place where the streets are not marked.",
           "Some windows are lighted. but mostly they're darked.",
           "But mostly they're darked.",
           "A place you could sprain both your elbow and chin!",
           "Do you dare to stay out? Do you dare to go in?",
           "How much can you lose? How much can you win?",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "Fame you'll be famous, as famous as can be, with everyone watching you win on TV, Except when they don't because sometimes they won't..",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "When you're in a Slump,",
           "you're not in for much fun.",
           "Un-slumping yourself",
           "is not easily done.",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "You won't lag behind, because you'll have the speed.",
           "You'll pass the whole gang and you'll soon take the lead.",
           "Wherever you fly, you'll be best of the best.",
           "Wherever you go, you will top all the rest.",
           "Except when you don't.",
           "Because, sometimes, you won't.",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "Onward up many a frightening creek, though your arms may get sore and your sneakers may leak. Oh! The places you'll go!",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "So...be your name Buxbaum or Bixby or Bray",
           "or Mordecai Ali Van Allen O'Shea,",
           "you're off to Great Places!",
           "Today is your day!",
           "Your mountain is waiting.",
           "So...get on your way!",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "And will you succeed?",
           "Yes! You will, indeed!",
           "( (98 and 3/4 percent guaranteed.)",
           "KID, YOU'LL MOVE MOUNTAINS!",
           "Out there things can happen, and frequently do,",
           "To people as brainy and footsy as you.",
           "And when things start to happen, don't worry, don't stew.",
           "Just go right along, you'll start happening too!",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "You can get so confused",
           "that you'll start in to race",
           "down long wiggled roads at a break-necking pace",
           "and grind on for miles across weirdish wild space,",
           "headed, I fear, toward a most useless place.",
           "The Waiting Place...",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "Kid, you'll move mountains.",
           "-- Dr. Seuss, Oh, The Places You'll Go!",
           "Oh, the places you'll go! There is fun to be done!",
           "There are points to be scored. There are games to be won.",
           "And the magical things you can do with that ball",
           "will make you the winning-est winner of all.",
           "Fame! You'll be as famous as famous can be,",
           "with the whole wide world watching you win on TV.",
           "Except when they don't",
           "Because, sometimes they won't.",
           "I'm afraid that some times",
           "you'll play lonely games too.",
           "Games you can't win",
           "'cause you'll play against you.",
           "-- Dr. Seuss, Oh, The Places You'll Go!",           
           "- Dr. Seuss")
seuss.corpus <- Corpus(DataframeSource(data.frame(seuss)))
seuss.corpus

inspect(seuss.corpus)

seuss.corpus[1]

writeLines(as.character(seuss.corpus[1]))

writeLines(as.character(seuss.corpus[1:3]))


```


```{r}

# Eliminating Extra Whitespace
seuss.clean<-tm_map(seuss.corpus, stripWhitespace)
# stemDocument
seuss.clean.stem<-tm_map(seuss.clean, stemDocument)

writeLines(as.character(seuss.clean.stem[1]))

seuss.clean.lc <- tm_map(seuss.clean, content_transformer(tolower))
writeLines(as.character(seuss.clean.lc[1]))

seuss.clean <- tm_map(seuss.clean.lc, removeWords, stopwords("english"))
writeLines(as.character(seuss.clean.lc[1]))


seuss.tdm <- TermDocumentMatrix(seuss.clean, control = list(minWordLength = 1))
seuss.tdm


inspect(seuss.tdm[11:33,1:33])


findFreqTerms(seuss.tdm, lowfreq=3)

findAssocs(seuss.tdm, 'brains', 0.40)

# Word Cloud
m <- as.matrix(seuss.tdm)
# calculate the frequency of words
m
v <- sort(rowSums(m), decreasing=TRUE)
v
myNames <- names(v)
d <- data.frame(word=myNames, freq=v)
wordcloud(d$word, d$freq, min.freq=5)
 
```


